 CLASS zcl_test_cds_booking_rph DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zcl_test_cds_booking_rph IMPLEMENTATION.
 ENDCLASS.
